language: php
php:
    - 7
    - 5.6
    - 5.5
    - 5.4
    - 5.3

before_script:
    - sudo add-apt-repository ppa:dns/gnu --yes
    - sudo apt-get install --only-upgrade autoconf
    - for file in tests/*.phpt; do grep $(basename $file) package.xml >/dev/null || (echo "Missing $file from package.xml" ; exit 1); done

script:
    - export NO_INTERACTION=1
    - export REPORT_EXIT_STATUS=1
    - export TEST_PHP_EXECUTABLE=`which php`
    - phpize
    - ./configure
    - make
    - php run-tests.php -d extension=bloomy.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

